# Default values for rest-api-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#####################
#  API
#####################
softconAPI:
  replicaCount: 3
  labelapp: softcon-app
  group: backend
  genericApp:
    name: softcon
    container:
      image: localhost:32000/softcon
      port: 5000
    ingress:
      name: softcon
      annotations:
        - key: nginx.ingress.kubernetes.io/enable-cors
          value: "true"
        - key: nginx.ingress.kubernetes.io/cors-allow-methods
          value: "PUT, GET, POST, OPTIONS"
        - key: nginx.ingress.kubernetes.io/cors-allow-origin
          value: "*"
        - key: nginx.ingress.kubernetes.io/cors-allow-credentials
          value: "true"
      hosts:
        - host: chart-example.local
          paths: []
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
     
    

#####################
#  UI
#####################
softconUI:
  replicaCount: 3
  labelapp: softcon-ui-app
  group: frontend
  genericApp:
    name: softcon-ui
    container:
      image: localhost:32000/softcon-ui
      port: 3000
    ingress:
      name: softcon-ui
    hosts:
        - host: chart-example.local
          paths: []
  autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    
