# Default values for rest-api-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#####################
#  API
#####################
softconAPI:
  replicaCount: 3
  labelapp: softcon-app
  version: v1.0.0
  genericApp:
    name: softcon
    container:
      image: localhost:32000/softcon
      port: 5000
    ingress:
      name: softcon
      hosts:
        - host: softcon-app-helm.com
          paths: 
              - path: /
                pathType: Prefix
                backend:
                  serviceName: softcon-loadbalance-service
                  servicePort: 8081
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
     
    

#####################
#  UI
#####################
softconUI:
  replicaCount: 3
  labelapp: softcon-ui-app
  version: v1.0.0
  genericApp:
    name: softcon-ui
    container:
      image: localhost:32000/softcon-ui
      port: 3000
    ingress:
      name: softcon-ui
      hosts:
          - host: softcon-app-ui-helm.com
            paths: 
              - path: /
                pathType: Prefix
                backend:
                  serviceName: softcon-ui-loadbalance-service
                  servicePort: 80
  autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    
