# Default values for softconAPI.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true
replicaCount: 3
labelapp: softcon-app
version: v1.0.0
genericApp:
  name: softcon
  container:
    image: localhost:32000/softcon
    port: 5000
  service:
    type: ClusterIP
    protocol: TCP
    port: 8080
  ingress:
    name: softcon
    hosts:
      - host: softcon-app-helm.com
        paths: 
            - path: /
              pathType: Prefix
              backend:
                serviceName: softcon-nodeport-service
                servicePort: 8081
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80