enabled: true
replicaCount: 3
labelapp: softcon-ui
version: v1.0.0
genericApp:
  name: softcon-ui
  container:
    image: localhost:32000/softcon-ui
    port: 3000
  service:
    type: ClusterIP
    protocol: TCP
    port: 8080
  ingress:
    name: softcon-ui
    hosts:
        - host: softcon-app-ui-helm.com
          paths: 
            - path: /
              pathType: Prefix
              backend:
                serviceName: softcon-ui-nodeport-service
                servicePort: 80
autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80