{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.genericApp.name }}-deployment
  labels:
    app: {{ .Values.labelapp }}
    version: {{ .Values.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.genericApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.genericApp.name }}
        version: {{ .Values.version }}
    spec:
      containers:
        - name: {{ .Values.genericApp.name }}-container
          image: "{{ .Values.genericApp.container.image }}:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.genericApp.container.port }}
{{- end }}